# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-13 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20171010_1139'),
        ('config', '0002_auto_20171009_1900'),
    ]

    operations = [
    ]
