# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='license_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Authors', verbose_name='Author'),
        ),
    ]
