# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_auto_20171023_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='license_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Authors', verbose_name='Author'),
        ),
    ]
