# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-23 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exercises', '0009_auto_20171023_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='created_by_user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
    ]
