# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-23 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_merge'),
        ('nutrition', '0004_mealitem_time'),
    ]

    operations = [
    ]
