# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-13 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_auto_20171013_1111'),
        ('email', '0002_auto_20171009_1900'),
    ]

    operations = [
    ]
