# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-12 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20171009_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_with_api',
            field=models.BooleanField(default=False, help_text='Check to show user was created by another user or by an applicationthrought an API', verbose_name='User Created by Third party application or User'),
        ),
    ]
