# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-13 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20171012_1758'),
        ('core', '0010_auto_20171013_1111'),
    ]

    operations = [
    ]
