# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-19 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the author or source here of an Exercise. This is needed for some licenses e.g. the CC-BY-SA.', max_length=50, verbose_name='License Author')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
