# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-16 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='workoutlog',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workoutlog', to='manager.WorkoutLog'),
            preserve_default=False,
        ),
    ]
