# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-16 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_workoutsession_workoutlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='workoutlog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workoutlog', to='manager.WorkoutLog'),
        ),
    ]
