# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-16 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20171016_1157'),
        ('manager', '0010_merge'),
    ]

    operations = [
    ]
